name: sdienv
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - matplotlib=3.7.2
  - mkl=2023.1.0
  - networkx=3.1
  - nltk=3.8.1
  - numpy=1.24.3
  - pandas=2.0.3
  - pip=23.2.1
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - statsmodels=0.14.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - pip:
      - pyyaml==6.0.1
      - quapy==0.1.7
      - typing-extensions==4.12.2